theme: jekyll-theme-minimal
title: Personal AI for Alzheimer
description: Reviving precious memories and rekindling connections: our AI solution integrates seamlessly into everyday conversations, helping Alzheimer's patients recall cherished moments for a more normal, familiar interaction with loved ones, just like the good old days. 
